const express = require('express');
const router  = express.Router();
const ctrl    = require('../controllers/noticeController');
const { protect, authorize } = require('../middleware/auth');
const upload  = require('../middleware/upload');
router.use(protect);
router.get('/',        ctrl.getNotices);
router.post('/',       authorize('admin'), upload.single('attachment'), ctrl.createNotice);
router.get('/:id',     ctrl.getNotice);
router.put('/:id',     authorize('admin'), ctrl.updateNotice);
router.delete('/:id',  authorize('admin'), ctrl.deleteNotice);
module.exports = router;
