// const express  = require('express');
// const router   = express.Router();
// const ctrl     = require('../controllers/studentController');
// const {protect,authorize} = require('../middleware/auth');
// const upload   = require('../middleware/upload');
// router.use(protect);
// router.get('/stats',ctrl.getStats);
// router.get('/class/:classId',ctrl.getStudentsByClass);
// router.get('/',ctrl.getStudents);
// router.post('/',authorize('admin'),upload.single('photo'),ctrl.createStudent);
// router.get('/:id',ctrl.getStudent);
// router.put('/:id',authorize('admin'),upload.single('photo'),ctrl.updateStudent);
// router.delete('/:id',authorize('admin'),ctrl.deleteStudent);
// module.exports = router;

const express  = require('express');
const router   = express.Router();
const ctrl     = require('../controllers/studentController');
// const {protect,authorize} = require('../middleware/auth');
const upload   = require('../middleware/upload');
// router.use(protect);

router.get('/stats',ctrl.getStats);
router.get('/class/:classId',ctrl.getStudentsByClass);
router.get('/',ctrl.getStudents);
router.post('/',upload.single('photo'),ctrl.createStudent);
router.get('/:id',ctrl.getStudent);
router.put('/:id',upload.single('photo'),ctrl.updateStudent);
router.delete('/:id',ctrl.deleteStudent);
module.exports = router;
